// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type CreateContactHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type CreateContactRequestBody struct {
	Model shared.CreateUpdateContact `json:"model"`
}

type CreateContactRequest struct {
	Headers CreateContactHeaders
	Request CreateContactRequestBody `request:"mediaType=application/json"`
}

// CreateContact201ApplicationJSON - Contact created
type CreateContact201ApplicationJSON struct {
	Errors   []shared.Errors   `json:"errors,omitempty"`
	Logs     []shared.Logs     `json:"logs,omitempty"`
	Model    *shared.Contact   `json:"model,omitempty"`
	Warnings []shared.Warnings `json:"warnings,omitempty"`
}

type CreateContactResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Contact created
	CreateContact201ApplicationJSONObject *CreateContact201ApplicationJSON
}
