// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type CreateOpportunityHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type CreateOpportunityRequestBody struct {
	Model shared.CreateUpdateOpportunity `json:"model"`
}

type CreateOpportunityRequest struct {
	Headers CreateOpportunityHeaders
	Request CreateOpportunityRequestBody `request:"mediaType=application/json"`
}

// CreateOpportunity201ApplicationJSON - Opportunity created
type CreateOpportunity201ApplicationJSON struct {
	Errors   []shared.Errors     `json:"errors,omitempty"`
	Logs     []shared.Logs       `json:"logs,omitempty"`
	Model    *shared.Opportunity `json:"model,omitempty"`
	Warnings []shared.Warnings   `json:"warnings,omitempty"`
}

type CreateOpportunityResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Opportunity created
	CreateOpportunity201ApplicationJSONObject *CreateOpportunity201ApplicationJSON
}
