// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type CreateAccountHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type CreateAccountRequestBody struct {
	Model shared.CreateUpdateAccount `json:"model"`
}

type CreateAccountRequest struct {
	Headers CreateAccountHeaders
	Request CreateAccountRequestBody `request:"mediaType=application/json"`
}

// CreateAccount201ApplicationJSON - Account created
type CreateAccount201ApplicationJSON struct {
	Errors   []shared.Errors   `json:"errors,omitempty"`
	Logs     []shared.Logs     `json:"logs,omitempty"`
	Model    *shared.Account   `json:"model,omitempty"`
	Warnings []shared.Warnings `json:"warnings,omitempty"`
}

type CreateAccountResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Account created
	CreateAccount201ApplicationJSONObject *CreateAccount201ApplicationJSON
}
