// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type GetLeadPathParams struct {
	LeadID string `pathParam:"style=simple,explode=false,name=lead_id"`
}

type GetLeadQueryParams struct {
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

type GetLeadHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type GetLeadRequest struct {
	PathParams  GetLeadPathParams
	QueryParams GetLeadQueryParams
	Headers     GetLeadHeaders
}

type GetLeadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Lead
	Lead *shared.Lead
}
