// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type GetOpportunityPathParams struct {
	OpportunityID string `pathParam:"style=simple,explode=false,name=opportunity_id"`
}

type GetOpportunityQueryParams struct {
	// Which relations should be returned in expanded form. Multiple relation names should be comma separated without spaces
	Expand *string `queryParam:"style=form,explode=true,name=expand"`
}

type GetOpportunityHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type GetOpportunityRequest struct {
	PathParams  GetOpportunityPathParams
	QueryParams GetOpportunityQueryParams
	Headers     GetOpportunityHeaders
}

type GetOpportunityResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Opportunity
	Opportunity *shared.Opportunity
}
