// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type GetUserPathParams struct {
	UserID string `pathParam:"style=simple,explode=false,name=user_id"`
}

type GetUserHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type GetUserRequest struct {
	PathParams GetUserPathParams
	Headers    GetUserHeaders
}

type GetUserResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// User
	User *shared.User
}
