// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type SearchOpportunitiesQueryParams struct {
	// The pagination cursor value
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return per page
	PageSize *string `queryParam:"style=form,explode=true,name=page_size"`
}

type SearchOpportunitiesHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type SearchOpportunitiesRequestBodyFilters struct {
	AccountID *shared.Filter `json:"account_id,omitempty"`
}

type SearchOpportunitiesRequestBody struct {
	Filters SearchOpportunitiesRequestBodyFilters `json:"filters"`
}

type SearchOpportunitiesRequest struct {
	QueryParams SearchOpportunitiesQueryParams
	Headers     SearchOpportunitiesHeaders
	Request     SearchOpportunitiesRequestBody `request:"mediaType=application/json"`
}

// SearchOpportunities200ApplicationJSON - Opportunities
type SearchOpportunities200ApplicationJSON struct {
	Next     *string              `json:"next,omitempty"`
	Previous *string              `json:"previous,omitempty"`
	Results  []shared.Opportunity `json:"results,omitempty"`
}

type SearchOpportunitiesResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Opportunities
	SearchOpportunities200ApplicationJSONObject *SearchOpportunities200ApplicationJSON
}
