// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type SearchContactsQueryParams struct {
	// The pagination cursor value
	Cursor *string `queryParam:"style=form,explode=true,name=cursor"`
	// Number of results to return per page
	PageSize *string `queryParam:"style=form,explode=true,name=page_size"`
}

type SearchContactsHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type SearchContactsRequestBodyFilters struct {
	EmailAddress *shared.Filter `json:"email_address,omitempty"`
}

type SearchContactsRequestBody struct {
	Filters SearchContactsRequestBodyFilters `json:"filters"`
}

type SearchContactsRequest struct {
	QueryParams SearchContactsQueryParams
	Headers     SearchContactsHeaders
	Request     SearchContactsRequestBody `request:"mediaType=application/json"`
}

// SearchContacts200ApplicationJSON - Contacts
type SearchContacts200ApplicationJSON struct {
	Next     *string          `json:"next,omitempty"`
	Previous *string          `json:"previous,omitempty"`
	Results  []shared.Contact `json:"results,omitempty"`
}

type SearchContactsResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Contacts
	SearchContacts200ApplicationJSONObject *SearchContacts200ApplicationJSON
}
