// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type UpdateLeadPathParams struct {
	LeadID string `pathParam:"style=simple,explode=false,name=lead_id"`
}

type UpdateLeadHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type UpdateLeadRequestBody struct {
	Model shared.CreateUpdateLead `json:"model"`
}

type UpdateLeadRequest struct {
	PathParams UpdateLeadPathParams
	Headers    UpdateLeadHeaders
	Request    UpdateLeadRequestBody `request:"mediaType=application/json"`
}

// UpdateLead200ApplicationJSON - Lead updated
type UpdateLead200ApplicationJSON struct {
	Errors   []shared.Errors   `json:"errors,omitempty"`
	Logs     []shared.Logs     `json:"logs,omitempty"`
	Model    *shared.Lead      `json:"model,omitempty"`
	Warnings []shared.Warnings `json:"warnings,omitempty"`
}

type UpdateLeadResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Lead updated
	UpdateLead200ApplicationJSONObject *UpdateLead200ApplicationJSON
}
