// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type UpdateOpportunityPathParams struct {
	OpportunityID string `pathParam:"style=simple,explode=false,name=opportunity_id"`
}

type UpdateOpportunityHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type UpdateOpportunityRequestBody struct {
	Model shared.CreateUpdateOpportunity `json:"model"`
}

type UpdateOpportunityRequest struct {
	PathParams UpdateOpportunityPathParams
	Headers    UpdateOpportunityHeaders
	Request    UpdateOpportunityRequestBody `request:"mediaType=application/json"`
}

// UpdateOpportunity200ApplicationJSON - Opportunity updated
type UpdateOpportunity200ApplicationJSON struct {
	Errors   []shared.Errors     `json:"errors,omitempty"`
	Logs     []shared.Logs       `json:"logs,omitempty"`
	Model    *shared.Opportunity `json:"model,omitempty"`
	Warnings []shared.Warnings   `json:"warnings,omitempty"`
}

type UpdateOpportunityResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Opportunity updated
	UpdateOpportunity200ApplicationJSONObject *UpdateOpportunity200ApplicationJSON
}
