// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package operations

import (
	"net/http"
	"supaglue/pkg/models/shared"
)

type UpdateContactPathParams struct {
	ContactID string `pathParam:"style=simple,explode=false,name=contact_id"`
}

type UpdateContactHeaders struct {
	// The customer ID that uniquely identifies the customer in your application
	XCustomerID string `header:"style=simple,explode=false,name=x-customer-id"`
	// The provider name
	XProviderName string `header:"style=simple,explode=false,name=x-provider-name"`
}

type UpdateContactRequestBody struct {
	Model shared.CreateUpdateContact `json:"model"`
}

type UpdateContactRequest struct {
	PathParams UpdateContactPathParams
	Headers    UpdateContactHeaders
	Request    UpdateContactRequestBody `request:"mediaType=application/json"`
}

// UpdateContact200ApplicationJSON - Contact updated
type UpdateContact200ApplicationJSON struct {
	Errors   []shared.Errors   `json:"errors,omitempty"`
	Logs     []shared.Logs     `json:"logs,omitempty"`
	Model    *shared.Contact   `json:"model,omitempty"`
	Warnings []shared.Warnings `json:"warnings,omitempty"`
}

type UpdateContactResponse struct {
	ContentType string
	StatusCode  int
	RawResponse *http.Response
	// Contact updated
	UpdateContact200ApplicationJSONObject *UpdateContact200ApplicationJSON
}
