// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Account - Account
type Account struct {
	Addresses         []Addresses    `json:"addresses"`
	CreatedAt         time.Time      `json:"created_at"`
	Description       string         `json:"description"`
	ID                string         `json:"id"`
	Industry          string         `json:"industry"`
	LastActivityAt    time.Time      `json:"last_activity_at"`
	Name              string         `json:"name"`
	NumberOfEmployees int64          `json:"number_of_employees"`
	Owner             *User          `json:"owner,omitempty"`
	OwnerID           string         `json:"owner_id"`
	PhoneNumbers      []PhoneNumbers `json:"phone_numbers"`
	RemoteID          string         `json:"remote_id"`
	UpdatedAt         time.Time      `json:"updated_at"`
	Website           string         `json:"website"`
}
