// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Contact - Contact
type Contact struct {
	Account        *Account         `json:"account,omitempty"`
	AccountID      string           `json:"account_id"`
	Addresses      []Addresses      `json:"addresses"`
	CreatedAt      time.Time        `json:"created_at"`
	EmailAddresses []EmailAddresses `json:"email_addresses"`
	FirstName      string           `json:"first_name"`
	ID             string           `json:"id"`
	LastActivityAt time.Time        `json:"last_activity_at"`
	LastName       string           `json:"last_name"`
	Owner          *User            `json:"owner,omitempty"`
	OwnerID        string           `json:"owner_id"`
	PhoneNumbers   []PhoneNumbers   `json:"phone_numbers"`
	RemoteID       string           `json:"remote_id"`
	UpdatedAt      time.Time        `json:"updated_at"`
}
