// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateUpdateOpportunity struct {
	AccountID *string `json:"account_id,omitempty"`
	Amount    *int64  `json:"amount,omitempty"`
	CloseDate *string `json:"close_date,omitempty"`
	// Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API.
	CustomFields map[string]interface{} `json:"custom_fields,omitempty"`
	Description  *string                `json:"description,omitempty"`
	Name         *string                `json:"name,omitempty"`
	OwnerID      *string                `json:"owner_id,omitempty"`
	Stage        *string                `json:"stage,omitempty"`
}
