// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateUpdateLead struct {
	Addresses []Addresses `json:"addresses,omitempty"`
	Company   *string     `json:"company,omitempty"`
	// Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API.
	CustomFields   map[string]interface{} `json:"custom_fields,omitempty"`
	EmailAddresses []EmailAddresses       `json:"email_addresses,omitempty"`
	FirstName      *string                `json:"first_name,omitempty"`
	LastName       *string                `json:"last_name,omitempty"`
	LeadSource     *string                `json:"lead_source,omitempty"`
	OwnerID        *string                `json:"owner_id,omitempty"`
	Title          *string                `json:"title,omitempty"`
}
