// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type CreateUpdateAccount struct {
	Addresses []Addresses `json:"addresses,omitempty"`
	// Custom properties to be inserted that are not covered by the common model. Object keys must match exactly to the corresponding provider API.
	CustomFields      map[string]interface{} `json:"custom_fields,omitempty"`
	Description       *string                `json:"description,omitempty"`
	Industry          *string                `json:"industry,omitempty"`
	Name              *string                `json:"name,omitempty"`
	NumberOfEmployees *int64                 `json:"number_of_employees,omitempty"`
	OwnerID           *string                `json:"owner_id,omitempty"`
	PhoneNumbers      []PhoneNumbers         `json:"phone_numbers,omitempty"`
	Website           *string                `json:"website,omitempty"`
}
