// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type ErrorsSource struct {
	Pointer *string `json:"pointer,omitempty"`
}

type Errors struct {
	Detail      *string       `json:"detail,omitempty"`
	ProblemType *string       `json:"problem_type,omitempty"`
	Source      *ErrorsSource `json:"source,omitempty"`
	Title       *string       `json:"title,omitempty"`
}
