// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Lead - Lead
type Lead struct {
	Addresses          []Addresses      `json:"addresses"`
	Company            string           `json:"company"`
	ConvertedAccount   *Account         `json:"converted_account,omitempty"`
	ConvertedAccountID string           `json:"converted_account_id"`
	ConvertedContact   *Contact         `json:"converted_contact,omitempty"`
	ConvertedContactID string           `json:"converted_contact_id"`
	ConvertedDate      time.Time        `json:"converted_date"`
	CreatedAt          time.Time        `json:"created_at"`
	EmailAddresses     []EmailAddresses `json:"email_addresses,omitempty"`
	FirstName          *string          `json:"first_name,omitempty"`
	ID                 string           `json:"id"`
	LastName           string           `json:"last_name"`
	LeadSource         string           `json:"lead_source"`
	Owner              *User            `json:"owner,omitempty"`
	OwnerID            string           `json:"owner_id"`
	PhoneNumbers       []PhoneNumbers   `json:"phone_numbers"`
	RemoteID           string           `json:"remote_id"`
	Title              string           `json:"title"`
	UpdatedAt          time.Time        `json:"updated_at"`
}
