// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// Opportunity - Opportunity
type Opportunity struct {
	Account        *Account   `json:"account,omitempty"`
	AccountID      string     `json:"account_id"`
	Amount         int64      `json:"amount"`
	CloseDate      *time.Time `json:"close_date,omitempty"`
	CreatedAt      time.Time  `json:"created_at"`
	Description    string     `json:"description"`
	ID             string     `json:"id"`
	LastActivityAt time.Time  `json:"last_activity_at"`
	Name           string     `json:"name"`
	Owner          *User      `json:"owner,omitempty"`
	OwnerID        string     `json:"owner_id"`
	RemoteID       string     `json:"remote_id"`
	Stage          string     `json:"stage"`
	Status         string     `json:"status"`
	UpdatedAt      time.Time  `json:"updated_at"`
}
