// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"encoding/json"
	"fmt"
)

type PhoneNumbersPhoneNumberTypeEnum string

const (
	PhoneNumbersPhoneNumberTypeEnumPrimary PhoneNumbersPhoneNumberTypeEnum = "primary"
	PhoneNumbersPhoneNumberTypeEnumMobile  PhoneNumbersPhoneNumberTypeEnum = "mobile"
	PhoneNumbersPhoneNumberTypeEnumFax     PhoneNumbersPhoneNumberTypeEnum = "fax"
)

func (e *PhoneNumbersPhoneNumberTypeEnum) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	switch s {
	case "primary":
		fallthrough
	case "mobile":
		fallthrough
	case "fax":
		*e = PhoneNumbersPhoneNumberTypeEnum(s)
		return nil
	default:
		return fmt.Errorf("invalid value for PhoneNumbersPhoneNumberTypeEnum: %s", s)
	}
}

type PhoneNumbers struct {
	PhoneNumber     string                          `json:"phone_number"`
	PhoneNumberType PhoneNumbersPhoneNumberTypeEnum `json:"phone_number_type"`
}
