// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

import (
	"time"
)

// User - User
type User struct {
	CreatedAt time.Time `json:"created_at"`
	Email     string    `json:"email"`
	ID        string    `json:"id"`
	IsActive  bool      `json:"is_active"`
	Name      string    `json:"name"`
	RemoteID  string    `json:"remote_id"`
	UpdatedAt time.Time `json:"updated_at"`
}
