// Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.

package shared

type WarningsSource struct {
	Pointer *string `json:"pointer,omitempty"`
}

type Warnings struct {
	Detail      *string         `json:"detail,omitempty"`
	ProblemType *string         `json:"problem_type,omitempty"`
	Source      *WarningsSource `json:"source,omitempty"`
	Title       *string         `json:"title,omitempty"`
}
